---
title: "The Journal of Visualization and Interaction"
subtitle: A [diamond open-access](https://en.wikipedia.org/wiki/Open_access#Diamond/platinum_OA) journal for the [InfoVis](http://ieeevis.org/) and [HCI](https://chi.acm.org/) communities.
freeze: true
---

## What Is JoVI?

_The Journal of Visualization and Interaction_ (JoVI) is an **open access** publication for scientific work related to the fields of visualization and human-computer interaction. Contributions to the journal include research in: 

* how people understand and interact with information and technology, 
* novel techniques/systems and their evaluations, 
* systematic literature reviews, 
* replication studies, and 
* comments on existing publications. 

Cross-disciplinary work from other fields such as statistics or psychology, which is relevant to the fields of visualization or human-computer interaction is also welcome. 


## Open by Default

JoVI strongly supports transparency and openness and implements it as a default to enable readers to scrutinize and build on the research. Submitted manuscripts must link to all raw data and replication material for any empirical components, all reproducibility code for any analysis or computational component, and all other relevant research material (such as software code, interview protocols, and preregistrations – [link to policy page]). Otherwise, the submission must **explain why the material cannot be shared**, e.g., in cases of privacy concerns.


## Interactive HTML

JoVI is a venue pushing the boundaries of how scholarly publications look. All articles will be **published in HTML**, and authors may use built-in interactive components such as expander boxes and videos and are welcome to experiment with **custom interactive javascript** so long as content remains archivable and accessible or has a backup such as a video or image. JoVI runs on a modern publishing platform, [Quarto](https://quarto.org/), which makes it easy to publish computational notebooks written in RMarkdown, Jupyter Notebook, or Observable.


## Credibility over Novelty

We consider _how research advances knowledge _rather than _superficial novelty _as a criterion for reviewing, and reviewing efforts are focused on the soundness of the methods used. Reviews aim to evaluate the credibility of a manuscript’s claims and the clarity of its evidence rather than reviewer preference. **Registered reports**, the submission of study plans prior to data collection, are therefore strongly encouraged by JoVI.


## Corrections, Comments, and Continued Conversation

As part of a commitment to a continuously corrected scientific record, endorsed publications in the journal are living documents, where Digital Object Identifier (DOI) versioning gives all publications an overarching DOI and a DOI specific to each revision, allowing easy publication revisions alongside stable citation. Moreover, to foster discussions that go beyond the initial reviewer/author exchanges, we welcome post-endorsement commentaries on articles.


## More Respectful of Everyone’s Time

JoVI respects the time and effort of both authors and reviewers. **Authors can expect that their submissions will not be rejected over easily fixable technicalities**. An editor will check the initial submission for obvious problems and allow authors to update it before the review process if necessary. Also, initial submissions to JoVI have flexible formatting requirements, meaning authors accustomed to other formats will only need to make minor changes before submitting. Authors can even submit a preprint DOI instead of uploading the submission. One difference about JoVI articles is the [structured abstract], which is intended to clearly communicate to reviewers and readers what the contributions, methods, and conclusions are at the start.


## A More Humane Process

JoVI aims for a collaborative, humane review process. Reviewing is implemented as a (potentially anonymous) discussion between the authors and the reviewers rather than a one-sided argument about whether to accept or reject a manuscript. To start a review conversation, the editor posts the reviews as the beginning of discussion threads. The conversation proceeds as a back and forth around each review between authors, reviewers, and any other interested parties with the goal of improving the work. 


## Transparent Reviews

JoVI does not publish a limited number of manuscripts and does not seek to have a certain rejection rate. **All submitted work, reviews, and discussions will be publicly available for other researchers to use**. Manuscripts that have successfully addressed all the issues raised by the reviewers and editorial team are considered “endorsed” by the editor and approving reviewers, not “accepted”** **by the JoVI. **To encourage accountability, editors’ names are listed on the articles they endorse, and reviewers may choose to be named or anonymous**. As articles are living documents, which versions have received endorsements are clearly indicated with the article. All submissions and their accompanying reviews and discussions remain accessible whether or not an article secures an endorsement or is retracted.


## Inclusive

JoVI is committed to diversity, equity, and inclusion (DEI). The journal strives to maintain an editorial board with diverse representation in terms of gender and gender expression, race and ethnicity, sexual orientation, age, ability, geographic location, and affiliation. We value diversity as an empowering force that leads to better, more innovative, and more impactful research. **We commit to DEI by requiring editors, authors, and reviewers to follow our [code of conduct]**, and any who do not do so will lose the opportunity to review for or contribute to JoVI in the future. Part of our commitment also involves being sensitive to contributors at different stages of their careers; as such, we allow reviewers to review anonymously and authors to opt for anonymity prior to the first endorsement. We also strive for all endorsed articles to be accessible to people of different abilities.
