---
title: "Organizers"
sidebar: false
---

To contact the JoVI organizing committee, email [organizers@journalovi.org](mailto:organizers@journalovi.org).
For submission inquiries, email [submit@journalovi.org](mailto:submit@journalovi.org).

The JoVI organizers (in alphabetical order) are:

- [Lonni Besançon](https://lonnibesancon.me/), Monash University
- [Florian Echtler](https://floe.butterbrot.org/), Aalborg University
- [Matthew Kay](https://www.mjskay.com/), Northwestern University
- [Chat Wacharamanotham](https://chatchavan.github.io), Swansea University

JoVI also owes a huge debt to [Steve Haroz](http://steveharoz.com/), who was instrumental in its formation and early iterations.

## Advisory Board

- Pierre Dragicevic, Inria Bordeaux
- Jason Dykes, City, University of London
- Kasper Hornbæk, University of Copenhagen
- Eva Hornecker, Bauhaus-Universität Weimar
- Jessica Hullman, Northwestern University
- Yvonne Jansen, CNRS
- Amelia McNamara, University of St Thomas
- Arvind Satyanarayan, MIT CSAIL
- Carlos Scheidegger, Posit
- Jon Schwabish, Urban Institute

## Accessibility Chair

- Dominik Moritz, Carnegie Mellon University ([accessibility@journalovi.org](mailto:accessibility@journalovi.org))

## Associate Editors

- Leilani Battle, University of Washington
- Jason Dykes, City, University of London
- Niklas Elmqvist, University of Maryland, College Park
- Lane Harrison, Worcester Polytechnic Institute
- Yvonne Jansen, CNRS
- Clemens Nylandsted Klokmose, Aarhus University
- Houda Lamqaddam, University of Amsterdam
- Lace Padilla, University of California, Merced
- Jon Schwabish, Urban Institute
- Raphael Wimmer, University of Regensburg

## Publisher

Aalborg University Press<br/>
Kroghstræde 3<br/>
9220 Aalborg Ø<br/>
DENMARK

ISSN 2794-5502
