---
title: "People"
sidebar: false
---

To contact the JoVI organizing committee, email [organizers@journalovi.org](mailto:organizers@journalovi.org).
For submission inquiries, email [submit@journalovi.org](mailto:submit@journalovi.org).

## Organizing Committee

The JoVI organizers (in alphabetical order) are:

- [Lonni Besançon](https://lonnibesancon.me/), Department of Science & Technology, Linköping University (Github ID: [@lonnibesancon](https://github.com/lonnibesancon))
- [Florian Echtler](https://floe.butterbrot.org/), Department of Computer Science, Aalborg University (Github ID: [@floe](https://github.com/floe))
- [Matthew Kay](https://www.mjskay.com/), Department of Computer Science & Communication, Northwestern University (Github ID: [@mjskay](https://github.com/mjskay))
- [Chat Wacharamanotham](https://chatchavan.github.io), Department of Informatics, University of Zurich (Github ID: [@chatchavan](https://github.com/chatchavan))

JoVI also owes a huge debt to [Steve Haroz](http://steveharoz.com/), who was instrumental in its formation and early iterations.

## Advisory Board

- Pierre Dragicevic, Inria Bordeaux
- Jason Dykes, City, University of London
- Jeffrey Heer, University of Washington
- Kasper Hornbæk, University of Copenhagen
- Eva Hornecker, Bauhaus-Universität Weimar
- Jessica Hullman, Northwestern University
- Yvonne Jansen, CNRS
- Amelia McNamara, University of St Thomas
- Arvind Satyanarayan, MIT CSAIL
- Carlos Scheidegger, Posit
- Jon Schwabish, Urban Institute

## Accessibility Chair

- Dominik Moritz, Carnegie Mellon University ([accessibility@journalovi.org](mailto:accessibility@journalovi.org))  (Github ID: [@domoritz](https://github.com/domoritz))

## Open Practices Chairs

- Charles Cui, Northwestern University (Github ID: [@digital-flaneur](https://github.com/digital-flaneur))
- Lily Ge, Northwestern University (Github ID: [@lily-ge](https://github.com/lily-ge))
- Maxim Lisnic, University of Utah (Github ID: [@mlisnic](https://github.com/mlisnic))
- Sheng Long, Northwestern University (Github ID: [@mika-long](https://github.com/mika-long))
- Vahid Pooryousef, Monash University (Github ID: [@vahpy](https://github.com/vahpy))
- Abhraneel Sarma, Northwestern University (Github ID: [@abhsarma](https://github.com/abhsarma))

## Associate Editors

- Leilani Battle, University of Washington
- Cindy Xiong Bearfield, Georgia Institute of Technology
- Jason Dykes, City, University of London
- Frank Elavsky, Carnegie Mellon University
- Niklas Elmqvist, Aarhus University
- James Eagan, Institut Polytechnique de Paris
- Nicolai B. Hansen, Aalborg University
- Lane Harrison, Worcester Polytechnic Institute
- Yvonne Jansen, CNRS
- Miguel Nacenta, University of Victoria
- Andrew McNutt, University of Utah
- Clemens Nylandsted Klokmose, Aarhus University
- Houda Lamqaddam, University of Amsterdam
- Lace Padilla, Northeastern University
- Evan Peck, University of Colorado Boulder
- Charles Perin, University of Victoria
- Jon Schwabish, Urban Institute
- Michael Sedlmair, University of Stuttgart
- Emily Wall, Emory University
- Wesley Willett, University of Calgary
- Raphael Wimmer, University of Regensburg
- Jessica K. Witt, Colorado State University
- Fumeng Yang, Northwestern University
- Daniel Zielasko, Trier University

## Responsible Editor-in-Chief

Lonni Besançon, Linköping University

## Publisher

Aalborg University Open Publishing<br/>
Kroghstræde 1-3<br/>
9220 Aalborg Øst<br/>
DENMARK

ISSN 2794-5502
