---
title: "How to submit"
sidebar: false
---

Submissions are handled by an Action Editor who will assign each submission to three expert reviewers. Review proceeds as a dialogue between authors and reviewers, with the goal of improving the work. Authors can expect that their submissions will not be rejected over easily fixable technicalities.

All submitted work, reviews, and discussions will by default be publicly available for other researchers to use. To encourage accountability, editors’ names are listed on the articles they accept, and reviewers may choose to be named or anonymous. All submissions and their accompanying reviews and discussions remain accessible whether or not an article is accepted.

JoVI encourages [registered reports](https://www.cos.io/initiatives/registered-reports), which follow a two-stage submission and review process. In the first stage, authors submit a paper that contains all plans, methods, and research questions, prior to any data collection. Through dialogue and discussion, reviewers and authors agree on revised plans, methods, and research questions.  Then authors can collect and analyze data and write the final version of the paper, which will get a lightweight second-stage review by the same reviewers (except in extenuating circumstances).


JoVI has two submission tracks: the [traditional track](#traditional) and the [experimental ("Github") track](#experimental).

## Traditional track {#traditional}

You may prepare your paper with any academic paper template that you are familiar with, from IEEE, ACM, EuroGraphics, APA, or other well-known journals or conferences. However, we strongly recommend the [ACM template](https://www.acm.org/publications/proceedings-template) or the [IEEE TVCG template](https://tc.computer.org/vgtc/publications/journal/).

JoVI has the following additional requirements:

-   Paper size: Either ISO A4 or US-Letter.
-   The page orientation must be portrait.
-   The layout is single-column.
-   Line heights for body text between 1.0x and 1.7x. Double-spaced body text, which is common in APA submissions, is not allowed.
-   We recommend 1.2x line spacing and a single column with 1.5-inch margins on the sides.
-   Figures, tables, and their captions must be in the body text rather than all at the end.

Submission for the traditional track proceeds via the [OJS submission system](https://journals.aau.dk/index.php/jovi/), hosted courtesy of the Aalborg University Library. Please create an OJS account, preferably using your default institutional email address, and follow the instructions on OJS to submit your paper and supplementary materials. 

To submit:

1. Please read the [Author Guidelines](author-guide.qmd), even if you are a seasoned HCI/VIS researcher. JoVI's process and expectations may be a bit different from what you are used to. 
2. Start:
    * Go to [JoVI's OJS page](https://journals.aau.dk/index.php/jovi/submission/wizard)
    * Create an account and/or log in, if needed
    * Complete all submission requirements
    * If you are submitting anonymously, please indicate so in the `Comments for the Editor` section.
    * Click *Save and continue*
3. Upload submission:
    * Click *Add file*, upload main PDF
    * Select "article text" as type
    * Upload other files, if desired. 
    * If you are submitting anonymously, you may need to upload non-anonymous versions containing [required sections](author-guide.qmd#sections). Please name your file with the prefix `[non-anonymous]`. After uploading it, select the type `Author Information`.
    * Click *Save and continue*
4. Enter Metadata:
    * Add title and abstract
    * Add co-authors: click *add contributor*, fill form
        * Select *Author* as role
        * If you create accounts for your co-authors, we recommend ticking *Include contributor in browse lists* so that co-authors' accounts can be found later in search boxes.
    * Optional: fill in extra metadata
    * Click *Save and continue*
5. Confirmation:
    * Click *Finish submission*

## Experimental ("Github") track {#experimental}

The experimental track is an alternative submission and review process that manifests our [commitment to experimenting with review processes](index.qmd#ambitions). This track is less well-defined, in part because we wish it to evolve with authors as we use it.

### Submission format
Papers on the "Github" track can be written in **any format that renders to standalone HTML + Javascript**. Some formats you might consider are:

- [Quarto](https://quarto.org/), a markdown-based computational notebook format. This is our **recommended format**. You can use the our **[Quarto template for JoVI articles](https://github.com/journalovi/jovi-template-quarto)**. A live preview of this template is available [here](https://www.journalovi.org/jovi-template-quarto/). Quarto is a plain text format that can be used with documents written in a variety of forms (RMarkdown, Jupyter notebook, Word, Latex), and supports embedded computation (in many languages, including R, Python, and Julia) and **interactivity** (using JavaScript / Observable, d3, etc). 

- [Idyll](https://idyll-lang.org/), another markdown-based notebook format.

- Raw HTML + JavaScript, perhaps using a template designed for scholarly articles, such as [Distill](https://distill.pub/guide/).

- Any web workflow that renders to standalone HTML + JavaScript. **We welcome experimentation!**

We strongly prefer articles that do not require a live server. If your software requires server-side execution to work, see relevant instructions in the [author guide](https://www.journalovi.org/author-guide.html#what-if-my-interactive-article-requires-server-side-execution). 

If you are interested in trying another format and are not sure if it will work, [open an issue](https://github.com/journalovi/jovi-submissions/issues/new) on the `jovi-submissions` repository to ask about how we can help.

### How to submit

To submit to the experimental track, create an [article submission issue](https://github.com/journalovi/jovi-submissions/issues/new?assignees=mjskay&labels=submission&projects=&template=10_submit.yml&title=%5BSUBMISSION%5D+%3Ctitle%3E) on the `jovi-submissions` repository.

### Review process

All review on the experimental track proceeds as Github issues, and published papers on this track can be updated using pull requests, even after publication. The Github repository for each submission will be public throughout the process, regardless of the final decision on the submission. Therefore, while withdrawal of a submission is possible (in the sense that authors can ask for their paper not to be considered "published" at JoVI), the submitted paper and reviews will still be public even if the submission is withdrawn or is not accepted.


## Reviewing timeline

JoVI organizers process articles in batches at the end of each month, __except March and September__. Articles submitted by __the end of last Friday (AoE) of each month__ will be processed in that month's batch. The reviewing timeline is roughly as follows:

* Associate editor assignment usually takes two weeks.
* Reviewer invitation usually takes two weeks.
* After accepting the invitation, each reviewer has four--six weeks to write the review.
* After all reviews arrive, the associate editor may take two weeks to write their meta-review.
* The reviewing process usually has more than one round.
