---
title: "SIG @ CHI 2024"
description: "Experimenting with new review methods, open practices, and interactive publications in HCI"
author: "JoVI Organizing Committee"
date: "2024-04-04"
title-block-banner: true
categories:
  - News
  - Events
  - CHI
---

Are you going to CHI 2024 and interested in experimenting with new review methods, open practices, and interactive publications in HCI? Join us in a SIG meeting hosted by [JoVI](https://www.journalovi.org/) (the Journal of Visualization and Interaction).  We will specifically discuss topics surrounding the following question:

> How can we - and how should we - change the reviewing and publishing culture in HCI?

We want to hear from you: what would your ideal HCI publishing process look like? We will also share our experiences from the first year of [JoVI](https://www.journalovi.org/),  a diamond open-access, open review journal in HCI with an [explicit mission](https://www.journalovi.org/#ambitions) to continually experiment with new review processes and publication models.

The main event will be a Special Interest Group meeting (SIG) at the CHI 2024 conference on **16 May 11:00 (Hawaiʻi time) in room 318A**. We will also organize an online event synchronously at the same time.

## Goals of the event

As part of this SIG, we want to reflect on the first year of JoVI, which was first announced at CHI 2023. We will present some initial lessons learned from reviewing our first few submissions (including two traditional articles and five interactive articles), as well as current challenges we face.

We want to better understand current situations, issues, opportunities, and perspectives around open publishing and reviewing in HCI. We aim to gather diverse perspectives from stakeholders representing various roles in the publishing process (academics, industry researchers, authors, editors, reviewers, and students) to help brainstorm about what HCI publication could look like. 

Attendees' input will be gathered into a public document to be discussed by the [JoVI advisory board](https://www.journalovi.org/people.html#advisory-board) at their annual meeting, and will inform the future directions of JoVI.

## How to attend

1. SIG meeting:
   - **In-person:** If you want to participate in person at CHI 2024 in Hawaiʻi on Thursday 16 May 11:00 (Hawaiʻi timezone) at room 318A, you can just drop by!
   - **Online:** If you want to participate online, please register [here](https://uzh.zoom.us/meeting/register/u5EofuqqqjguHdLL5ecILlw-R7bNZq5Awthj).

2. Regardless of your participation, if you have any thoughts on open publishing or reviewing in HCI, or pointers to other works (e.g., papers, blog posts, newsletter articles, opinion statements) about open publishing and reviewing in HCI which you would like us to consider, please share with us by emailing to [organizers@journalovi.org](mailto:organizers@journalovi.org) or by joining the Slack (see [here](https://www.journalovi.org/news.html))

## Please spread the word

If you know of other academics, researchers, students, or industry people who might be likely to give valuable input to this event, please let us know.

If you think your students or colleagues might be interested in attending this event, please forward them this post.
